import { createHash } from 'crypto';

/**
 * Provider-level idempotency key for SMS sends — architecture §11.
 *
 * Key shape: `sha256(tenant_id|candidate_id|template_id|template_version|yyyy-mm-dd)`
 * where yyyy-mm-dd is the UTC date portion of the scheduled-for instant.
 *
 * Guarantee: a duplicate dispatch of the same (tenant, candidate, template,
 * version, send-day) tuple produces the same key → the provider returns the
 * same message id → we never double-text a candidate on worker retry.
 *
 * Epic 4 will extend this to include `job_requirement_id` (currently '' as
 * placeholder). The shape is forward-compatible: adding a non-empty segment
 * produces a different hash, so existing deployments never collide with a
 * key generated by the new shape.
 */
export interface ComputeSmsIdempotencyKeyInput {
  tenantId: string;
  candidateId: string;
  templateId: string;
  templateVersion: number;
  /** ISO-8601 timestamp string; we take the UTC yyyy-mm-dd portion only. */
  scheduledFor: string;
  /** Job requirement id — reserved for Epic 4. Default '' for Story 3-1. */
  jobRequirementId?: string;
}

export function computeSmsIdempotencyKey(input: ComputeSmsIdempotencyKeyInput): string {
  if (!input.tenantId) throw new Error('computeSmsIdempotencyKey: tenantId required');
  if (!input.candidateId) throw new Error('computeSmsIdempotencyKey: candidateId required');
  if (!input.templateId) throw new Error('computeSmsIdempotencyKey: templateId required');
  if (!Number.isFinite(input.templateVersion) || input.templateVersion <= 0) {
    throw new Error('computeSmsIdempotencyKey: templateVersion must be a positive integer');
  }
  if (!input.scheduledFor) throw new Error('computeSmsIdempotencyKey: scheduledFor required');

  const day = utcDatePart(input.scheduledFor);
  const jobId = input.jobRequirementId ?? '';

  const payload = [
    input.tenantId,
    input.candidateId,
    jobId,
    input.templateId,
    String(input.templateVersion),
    day,
  ].join('|');

  return createHash('sha256').update(payload).digest('hex');
}

function utcDatePart(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) {
    throw new Error(`computeSmsIdempotencyKey: scheduledFor is not a valid ISO timestamp (${iso})`);
  }
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}
